import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getSidebar } from "@/server/getSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sidebarConfig = getSidebar();

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <div className="py-16">{children}</div>
        </div>
      </body>
    </html>
  );
}
